import { drillData } from "@/shared/interface/drill_interface";

const mockDrillData: drillData[] = [
  {
    id: "1",
    title: "Drill Site A",
    description: "Drilling for geological survey in Texas.",
    lng: -99.1332,
    lat: 31.9686,
    category: "Pit",
  },
  {
    id: "2",
    title: "Drill Site B",
    description: "Ongoing trench digging for gas line in Texas.",
    lng: -97.7431,
    lat: 30.2672,
    category: "Trench",
  },
  {
    id: "3",
    title: "Drill Site C",
    description: "New well for water extraction in Texas.",
    lng: -96.7969,
    lat: 32.7767,
    category: "Well",
  },
  {
    id: "4",
    title: "Drill Site D",
    description: "Pit created for mining operations in Texas.",
    lng: -95.3698,
    lat: 29.7604,
    category: "Pit",
  },
  {
    id: "5",
    title: "Drill Site E",
    description: "Trench built for oil pipeline in Texas.",
    lng: -98.4936,
    lat: 29.4241,
    category: "Trench",
  },
  {
    id: "6",
    title: "Drill Site F",
    description: "Well for groundwater extraction in Texas.",
    lng: -96.3477,
    lat: 30.5832,
    category: "Well",
  },
  {
    id: "7",
    title: "Drill Site G",
    description: "Pit for coal mining in Texas.",
    lng: -101.8552,
    lat: 33.5779,
    category: "Pit",
  },
  {
    id: "8",
    title: "Drill Site H",
    description: "New trench for infrastructure development in Texas.",
    lng: -100.483,
    lat: 31.4667,
    category: "Trench",
  },
  {
    id: "9",
    title: "Drill Site I",
    description: "Testing water levels in well in Texas.",
    lng: -97.5692,
    lat: 32.7254,
    category: "Well",
  },
  {
    id: "10",
    title: "Drill Site J",
    description: "Expanding mining pit in Texas.",
    lng: -98.1162,
    lat: 31.5493,
    category: "Pit",
  },
  {
    id: "11",
    title: "Drill Site K",
    description: "Trench created for road construction in Texas.",
    lng: -97.3964,
    lat: 27.8006,
    category: "Trench",
  },
  {
    id: "12",
    title: "Drill Site L",
    description: "Well drilled for agricultural purposes in Texas.",
    lng: -102.0745,
    lat: 31.8457,
    category: "Well",
  },
  {
    id: "13",
    title: "Drill Site M",
    description: "Pit for quarrying limestone in Texas.",
    lng: -97.1347,
    lat: 31.1171,
    category: "Pit",
  },
  {
    id: "14",
    title: "Drill Site N",
    description: "Trench for utility cables installation in Texas.",
    lng: -97.3961,
    lat: 33.2148,
    category: "Trench",
  },
  {
    id: "15",
    title: "Drill Site O",
    description: "Water well for local community in Texas.",
    lng: -99.7755,
    lat: 32.4521,
    category: "Well",
  },
  {
    id: "16",
    title: "Drill Site P",
    description: "Mining pit expansion project in Texas.",
    lng: -101.7074,
    lat: 35.201,
    category: "Pit",
  },
  {
    id: "17",
    title: "Drill Site Q",
    description: "New trench for underground gas pipes in Texas.",
    lng: -99.2402,
    lat: 32.7555,
    category: "Trench",
  },
  {
    id: "18",
    title: "Drill Site R",
    description: "Water well drilling for irrigation in Texas.",
    lng: -97.1447,
    lat: 30.2679,
    category: "Well",
  },
  {
    id: "19",
    title: "Drill Site S",
    description: "Pit for mining expansion in Texas.",
    lng: -103.307,
    lat: 31.8434,
    category: "Pit",
  },
  {
    id: "20",
    title: "Drill Site T",
    description: "Trench digging for sewage pipes in Texas.",
    lng: -100.3984,
    lat: 29.3657,
    category: "Trench",
  },
];

export default mockDrillData;
